"""fix card model for planner

Revision ID: 15a1111f496a
Revises: 9e5c06a1b951
Create Date: 2026-05-15 17:32:57.487783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15a1111f496a'
down_revision: Union[str, Sequence[str], None] = '9e5c06a1b951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('priority', sa.String(), nullable=True))
    op.alter_column('cards', 'due_date',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_foreign_key(None, 'cards', 'users', ['assigned_to'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.alter_column('cards', 'due_date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('cards', 'priority')
    # ### end Alembic commands ###
