"""add createdat and uniqueid to notification

Revision ID: 274f730fa18d
Revises: d7a321ab3399
Create Date: 2026-05-15 02:16:20.847641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '274f730fa18d'
down_revision: Union[str, Sequence[str], None] = 'd7a321ab3399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('board_id', sa.UUID(), nullable=True))
    op.alter_column('notifications', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('notifications', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('notifications', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('notifications', 'board_id')
    # ### end Alembic commands ###
