"""Cards Added

Revision ID: 30e07ef24591
Revises: 900e7102ce1c
Create Date: 2026-05-13 23:16:45.532405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30e07ef24591'
down_revision: Union[str, Sequence[str], None] = '900e7102ce1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.UUID(), nullable=False),
    sa.Column('board_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('boards', sa.Column('description', sa.String(), nullable=True))
    op.add_column('boards', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('lists', 'board_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('lists_board_id_fkey'), 'lists', type_='foreignkey')
    op.create_foreign_key(None, 'lists', 'boards', ['board_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lists', type_='foreignkey')
    op.create_foreign_key(op.f('lists_board_id_fkey'), 'lists', 'boards', ['board_id'], ['id'])
    op.alter_column('lists', 'board_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('boards', 'created_at')
    op.drop_column('boards', 'description')
    op.drop_table('cards')
    # ### end Alembic commands ###
