"""add archived to board

Revision ID: 31bd66d78a3d
Revises: 59829c66439c
Create Date: 2026-05-21 19:27:13.711622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31bd66d78a3d'
down_revision: Union[str, Sequence[str], None] = '59829c66439c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boards', 'archived')
    # ### end Alembic commands ###
