"""changed card modal

Revision ID: 3274ea05e556
Revises: 983bec94c830
Create Date: 2026-06-11 11:40:37.524110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3274ea05e556'
down_revision: Union[str, Sequence[str], None] = '983bec94c830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
    """
    ALTER TABLE cards
    ALTER COLUMN due_date
    TYPE TIMESTAMP WITHOUT TIME ZONE
    USING due_date::timestamp;
    """
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
op.execute(
        """
        ALTER TABLE cards
        ALTER COLUMN due_date
        TYPE VARCHAR
        USING due_date::text;
        """
    )

    # ### end Alembic commands ###
