"""add gender and professional_role

Revision ID: 32d984d5874c
Revises: dae226d67fa8
Create Date: 2026-06-05 11:11:34.461907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32d984d5874c'
down_revision: Union[str, Sequence[str], None] = 'dae226d67fa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('users', sa.Column('professional_role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'professional_role')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
