"""add card attachment

Revision ID: 4127c64b5bde
Revises: e62f2190df8a
Create Date: 2026-06-20 15:31:39.121016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4127c64b5bde'
down_revision: Union[str, Sequence[str], None] = 'e62f2190df8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('attachment_url', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('attachment_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'attachment_name')
    op.drop_column('cards', 'attachment_url')
    # ### end Alembic commands ###
