"""add title to notifications

Revision ID: 4b3d155ff5d2
Revises: 30e07ef24591
Create Date: 2026-05-14 12:58:41.038225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b3d155ff5d2'
down_revision: Union[str, Sequence[str], None] = '30e07ef24591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('board_id', sa.UUID(), nullable=True))
    op.alter_column('notifications', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('notifications', 'created_at')
    op.drop_column('notifications', 'type')
    op.drop_column('notifications', 'entity_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.alter_column('notifications', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('notifications', 'board_id')
    # ### end Alembic commands ###
