"""activitychanges

Revision ID: 59829c66439c
Revises: 63ad70d0e919
Create Date: 2026-05-19 14:37:31.170092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59829c66439c'
down_revision: Union[str, Sequence[str], None] = '63ad70d0e919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('depends_on', sa.UUID(), nullable=True))
    op.add_column('cards', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('cards', sa.Column('priority', sa.String(), nullable=True))
    op.create_foreign_key(None, 'cards', 'users', ['assigned_to'], ['id'])
    op.add_column('notifications', sa.Column('category', sa.String(), nullable=True))
    op.add_column('team_invites', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_invites', 'created_at')
    op.drop_column('notifications', 'category')
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.drop_column('cards', 'priority')
    op.drop_column('cards', 'completed_at')
    op.drop_column('cards', 'depends_on')
    # ### end Alembic commands ###
