"""add completed column

Revision ID: 6ddcf7ffbf84
Revises: 44b53c6c2c6b
Create Date: 2026-05-19 00:01:21.082267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ddcf7ffbf84'
down_revision: Union[str, Sequence[str], None] = '44b53c6c2c6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.alter_column('cards', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'cards', 'boards', ['board_id'], ['id'])
    op.create_foreign_key(None, 'cards', 'users', ['assigned_to'], ['id'])
    op.create_foreign_key(None, 'cards', 'lists', ['list_id'], ['id'])
    op.alter_column('team_invites', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('team_invites', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.alter_column('cards', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('cards', 'completed_at')
    # ### end Alembic commands ###
