"""add gender and professional_role to users

Revision ID: 6fad625f895a
Revises: c7662e4748f6
Create Date: 2026-06-05 13:26:07.672371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fad625f895a'
down_revision: Union[str, Sequence[str], None] = 'c7662e4748f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('users', sa.Column('professional_role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'professional_role')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
