"""clean schema

Revision ID: 7362fa4b8cb3
Revises: 
Create Date: 2026-05-13 15:24:46.385219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7362fa4b8cb3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('list_id', sa.UUID(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cards')
    op.drop_table('board_members')
    # op.add_column('boards', sa.Column('title', sa.String(), nullable=True))
    # op.drop_column('boards', 'is_archived')
    # op.drop_column('boards', 'name')
    # Add column as nullable first ✅
    op.add_column('boards', sa.Column('title', sa.String(), nullable=True))

# Fill existing rows ✅
    op.execute("UPDATE boards SET title = 'Default' WHERE title IS NULL")

# Make column NOT NULL ✅
    op.alter_column('boards', 'title', nullable=False)

# Now remove old columns ✅
    op.drop_column('boards', 'is_archived')
    op.drop_column('boards', 'name')
    op.alter_column('lists', 'position',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('lists', 'board_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('lists_board_id_fkey'), 'lists', type_='foreignkey')
    op.create_foreign_key(None, 'lists', 'boards', ['board_id'], ['id'], ondelete='CASCADE')
    op.drop_column('lists', 'is_archived')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lists', sa.Column('is_archived', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'lists', type_='foreignkey')
    op.create_foreign_key(op.f('lists_board_id_fkey'), 'lists', 'boards', ['board_id'], ['id'])
    op.alter_column('lists', 'board_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('lists', 'position',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('boards', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('boards', sa.Column('is_archived', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('boards', 'title')
    op.create_table('board_members',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('board_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], name=op.f('board_members_board_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('board_members_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('board_members_pkey'))
    )
    op.create_table('cards',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('board_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assigned_to', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_archived', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('board_list_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('cards_assigned_to_fkey')),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], name=op.f('cards_board_id_fkey')),
    sa.ForeignKeyConstraint(['board_list_id'], ['lists.id'], name=op.f('cards_board_list_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cards_pkey'))
    )
    op.drop_table('tasks')
    op.drop_table('notifications')
    # ### end Alembic commands ###
