"""update models for badge

Revision ID: 941f7aaaf74e
Revises: 2e38c4386318
Create Date: 2026-05-31 21:14:55.278988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '941f7aaaf74e'
down_revision: Union[str, Sequence[str], None] = '2e38c4386318'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('badge', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'badge')
    # ### end Alembic commands ###
