"""Teams table Added

Revision ID: 9e5c06a1b951
Revises: 4a3432965c09
Create Date: 2026-05-15 12:02:45.751640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e5c06a1b951'
down_revision: Union[str, Sequence[str], None] = '4a3432965c09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_invites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('boards', sa.Column('team_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'boards', 'teams', ['team_id'], ['id'])
    op.alter_column('cards', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cards', 'due_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('cards_assigned_to_fkey'), 'cards', type_='foreignkey')
    op.drop_column('cards', 'priority')
    op.add_column('notifications', sa.Column('type', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('entity_id', sa.UUID(), nullable=True))
    op.add_column('notifications', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'created_at')
    op.drop_column('notifications', 'entity_id')
    op.drop_column('notifications', 'type')
    op.add_column('cards', sa.Column('priority', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('cards_assigned_to_fkey'), 'cards', 'users', ['assigned_to'], ['id'])
    op.alter_column('cards', 'due_date',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('cards', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'boards', type_='foreignkey')
    op.drop_column('boards', 'team_id')
    op.drop_table('team_members')
    op.drop_table('team_invites')
    op.drop_table('teams')
    # ### end Alembic commands ###
