"""add archived to team

Revision ID: ac88d8b53b8a
Revises: 31bd66d78a3d
Create Date: 2026-05-21 22:36:59.351155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac88d8b53b8a'
down_revision: Union[str, Sequence[str], None] = '31bd66d78a3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'archived')
    # ### end Alembic commands ###
