"""add assigned_to and due_date to card

Revision ID: d7a321ab3399
Revises: 818301fdbbaf
Create Date: 2026-05-15 00:07:58.598774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7a321ab3399'
down_revision: Union[str, Sequence[str], None] = '818301fdbbaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('due_date', sa.String(), nullable=True))
    op.drop_constraint(op.f('cards_assigned_to_fkey'), 'cards', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('cards_assigned_to_fkey'), 'cards', 'users', ['assigned_to'], ['id'])
    op.drop_column('cards', 'due_date')
    # ### end Alembic commands ###
