"""add secondaryemail verification

Revision ID: da407831dfc3
Revises: d7ffb67885c8
Create Date: 2026-06-23 16:49:26.946365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da407831dfc3'
down_revision: Union[str, Sequence[str], None] = 'd7ffb67885c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('users', sa.Column('secondary_email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('secondary_email_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'secondary_email_verified')
    op.drop_column('users', 'secondary_email')

    # ### end Alembic commands ###
