"""add_query_reply

Revision ID: e62f2190df8a
Revises: 3274ea05e556
Create Date: 2026-06-18 12:14:37.630455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e62f2190df8a'
down_revision: Union[str, Sequence[str], None] = '3274ea05e556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('user_queries', sa.Column('admin_reply', sa.Text(), nullable=True))
    op.add_column('user_queries', sa.Column('replied', sa.Boolean(), nullable=True))
    op.add_column('user_queries', sa.Column('replied_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_queries', 'replied_at')
    op.drop_column('user_queries', 'replied')
    op.drop_column('user_queries', 'admin_reply')

    # ### end Alembic commands ###
